### ISSUE TITLE
【问题】：我在局域网的另一台机器76部署了tarsnode，在57:3000的节点列表无法联通76

### ISSUE THREAD

**Issue by Lands-1203** [TarsCloud/Tars#898]
![image](https://github.com/TarsCloud/Tars/assets/61341868/a89cdd45-c2f8-43a9-ba62-d59eb5f1af4a)
![image](https://github.com/TarsCloud/Tars/assets/61341868/1cc390cd-7923-4c73-9dad-14e20de968f1)
我应该怎么排查这个问题
```
#57的主节点配置
version: "3"
services:

  tars-mysql:
    image: mysql:5.6
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: "xxx"
      MYSQL_TCP_PORT: 3310
    restart: always
    volumes:
      - ~/app/tars/framework-mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime

  tars-framework:
    image: tarscloud/framework:v3.0.1
    network_mode: "host"
    environment:
      MYSQL_HOST: "10.10.141.57"
      MYSQL_ROOT_PASSWORD: "xxx"
      MYSQL_PORT: 3310
      TZ: "Asia/Shanghai"  # 设置容器内时区为亚洲/上海时区
      REBUILD: "false"
      INET: enp2s0
      SLAVE: "false"
    restart: always
    volumes:
      - ~/app/tars/framework:/data/tars
      - /etc/localtime:/etc/localtime
    depends_on:
      - tars-mysql
```
tarsnode是使用docker-compose安装的
```
# 76的node配置
version: "3"
services:
  tars-node:
    image: tarscloud/tars-node:latest
    network_mode: "host"
    environment:
      INET: enp2s0
      WEB_HOST: "http://10.10.141.57:3000"
    restart: always
    volumes:
      - ~/app/tars:/data/tars
      - /etc/localtime:/etc/localtime
```
